#!/usr/bin/ansible-playbook
- name:
  hosts: mm
  vars:
    dns:
      admin_url: http://192.168.178.30/admin/
  any_errors_fatal: false
  serial: 1
  become: false
  tasks:

  ## VPN 
  - name: ping VPN server
    command: "ping 10.8.0.1 -c 3 -W 8"
    register: ping_result
    #failed_when: ping_result.stdout == 1
    changed_when: ping_result.rc == 1
    ignore_errors: yes

  - name: restart vpn
    command: pwd
    changed_when: ping_result.rc == 1
    notify: restart vpn

  - debug:
      var: ping_result
    #when: ping_result.rc == 1

#    when: ping_result.rc == 1
#    notify: restart mm
#    register: openvpn_restarted

  - debug:
      var: ping_result.rc
#      var: ping_result.rc, openvpn_restarted.state

  - name: nslookup deps
    become: yes
    apt:
      name: dnsutils
      state: present


  - name: Google nslookup check
    command: nslookup google.com 1.1.1.1
    ignore_errors: yes
    register: result
    changed_when: result.rc == 0

  - debug:
      var: result
    when: result.rc != 0


  # restart MagicMirror
  - name: "status pm2"
    shell:
      cmd: pm2 status | grep MagicMirror | grep enabled
    register: pm2status
    ignore_errors: yes
    changed_when:  "'FAILED' in pm2status.stderr"

  - name: restart pm2 check
    command: pwd
    when: pm2status.rc == 1
    notify: restart mm

  - debug:
      var: pm2status
    #when: "'FAILED' in pm2status.stderr"

  handlers:
    - name: restart mm
      listen: "restart mm"
      command: pm2 restart 0

    - name: restart vpn
      listen: "restart vpn"
      become: yes
      service:
        name: openvpn
        state: restarted
      when: ping_result.rc == 1
