#!/usr/bin/env ansible-playbook
- name:
  hosts: mm
  #any_errors_fatal: false
  #serial: 1
  become: false
  ignore_errors: yes
  tasks:

  ## VPN 
  - name: ping VPN server
    command: "ping 10.8.0.1 -c 3 -W 8"
    register: ping_result
    #failed_when: ping_result.stdout == 1
    changed_when: ping_result.rc != 0
    

  - name: restart vpn
    command: pwd
    changed_when: ping_result.rc != 0
    notify: restart vpn

  - debug:
      var: ping_result
    when: ping_result.rc != 0

  - debug:
      var: ping_result.rc
    when: False

  - name: nslookup deps
    become: yes
    apt:
      name: dnsutils
      state: present


  - name: Google nslookup check
    command: nslookup google.com 1.1.1.1
    ignore_errors: yes
    register: result
    changed_when: result.rc != 0

  - debug:
      var: result
    when: result.rc != 0


  # restart MagicMirror
  - name: "status pm2"
    become_user: pi
    shell:
#      cmd: sudo -u pi pm2 status mm
      cmd: pm2 status mm
    register: pm2status
    #ignore_errors: yes
    changed_when:  "'online' not in pm2status.stdout and 'enabled' not in pm2status.stdout"

  - debug:
      var: pm2status
    when: "'online' not in pm2status.stdout and 'enabled' not in pm2status.stdout"

  - name: restart mm
    become_user: pi
#      listen: "restart mm"
    command: pm2 restart mm
    when: "'online' not in pm2status.stdout and 'enabled' not in pm2status.stdout"
    register: pm2restart

  - debug:
      var: pm2restart
    when: "'online' not in pm2status.stdout and 'enabled' not in pm2status.stdout"
  
  # this handler can be removed and added sequentially as a task. I will just leave it like this for now
  handlers:
    - name: restart vpn
#      listen: "restart vpn"
      become: yes
      service:
        name: openvpn
        state: restarted
      register: vpn_out

